title: Jisoo's Blog
description: Daily Review blog
author: 강지수 / Jisoo Kang
avatar: /jj.jpg
email: ji_soo_o@korea.ac.kr
skin: daylight
subscribe: False
location: korea 
comments:
  provider    : "disqus"                                # comment 처리 사이트 명칭 기재
              # false (default), "disqus", "discourse", "facebook"
              # "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname : "eona1301-github-io"                    # disqus의 shortname 기재
              # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-


plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 
google_analytics: G-ETCJG42GCW


# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
lang: kor

