title: Jisoo's Blog
description: Daily Review blog
author: 강지수 / Jisoo Kang
avatar: /me.jpg
email: ji_soo_o@korea.ac.kr
skin: daylight
subscribe: False
location: korea 
lang: kor
                  # disqus의 shortname 기재


plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 
google_analytics: G-ETCJG42GCW

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
disqus: 'https-jisoo0-0-github-io'  

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================


